using Test
using GraphMERT
using GraphMERT: Entity, Relation, KnowledgeGraph, MockLLMClient, evaluate_factscore, FActScoreResult

@testset "FActScore* with LLM Verification" begin
    # 1. Setup Mock KG
    e1 = Entity("e1", "Aspirin", "Drug")
    e2 = Entity("e2", "Headache", "Symptom")
    e3 = Entity("e3", "Nausea", "Symptom")
    e4 = Entity("e4", "Cancer", "Disease")
    
    # R1: Aspirin treats Headache (Supported)
    r1 = Relation("e1", "e2", "TREATS", 0.9)
    # R2: Aspirin causes Cancer (Contradicted)
    r2 = Relation("e1", "e4", "CAUSES", 0.8)
    # R3: Aspirin treats Nausea (Not Mentioned / Not Supported)
    r3 = Relation("e1", "e3", "TREATS", 0.7)
    
    kg = KnowledgeGraph(
        [e1, e2, e3, e4],
        [r1, r2, r3],
        Dict{String, Any}("domain" => "biomedical")
    )
    
    # 2. Setup Context Text
    text = "Aspirin is commonly used to treat headache. However, studies show it does not cause cancer. Some patients report side effects."
    
    # 3. Setup Mock LLM Client
    # We need to match the prompts generated by evaluate_triple_with_llm
    
    # Prompt for R1 (Supported)
    # Note: get_triple_context splits by punctuation and joins with space, losing punctuation
    # S1 contains both Aspirin and Headache
    ctx1 = "Aspirin is commonly used to treat headache"
    
    p1 = """
    Evaluate if the following relationship is supported by the context.
    
    Relationship: Aspirin --[TREATS]--> Headache

    Context: $ctx1

    Does the context support this relationship?
    Select one of:
    - SUPPORTED: The context explicitly confirms this relationship.
    - CONTRADICTED: The context explicitly contradicts this relationship.
    - NOT_MENTIONED: The context does not provide enough information.

    Answer with just the category name (SUPPORTED, CONTRADICTED, or NOT_MENTIONED).
    """

    # Prompt for R2 (Contradicted)
    # S1 has Aspirin, S2 has Cancer (fallback logic picks sentences with at least one entity)
    ctx2 = "Aspirin is commonly used to treat headache However, studies show it does not cause cancer"
    
    p2 = """
    Evaluate if the following relationship is supported by the context.
    
    Relationship: Aspirin --[CAUSES]--> Cancer

    Context: $ctx2

    Does the context support this relationship?
    Select one of:
    - SUPPORTED: The context explicitly confirms this relationship.
    - CONTRADICTED: The context explicitly contradicts this relationship.
    - NOT_MENTIONED: The context does not provide enough information.

    Answer with just the category name (SUPPORTED, CONTRADICTED, or NOT_MENTIONED).
    """

    # Prompt for R3 (Not Mentioned)
    # Nausea is not in text. Aspirin is in S1.
    ctx3 = "Aspirin is commonly used to treat headache"
    
    p3 = """
    Evaluate if the following relationship is supported by the context.
    
    Relationship: Aspirin --[TREATS]--> Nausea

    Context: $ctx3

    Does the context support this relationship?
    Select one of:
    - SUPPORTED: The context explicitly confirms this relationship.
    - CONTRADICTED: The context explicitly contradicts this relationship.
    - NOT_MENTIONED: The context does not provide enough information.

    Answer with just the category name (SUPPORTED, CONTRADICTED, or NOT_MENTIONED).
    """

    responses = Dict(
        p1 => "SUPPORTED",
        p2 => "CONTRADICTED",
        p3 => "NOT_MENTIONED"
    )
    
    llm_client = GraphMERT.create_mock_llm_client(responses)
    
    # 4. Run Evaluation
    # Note: relations have confidence 0.9, 0.8, 0.7. Default threshold is 0.5.
    @info "Entities in KG: $([e.id for e in kg.entities])"
    @info "Relations in KG: $([(r.head, r.relation_type, r.tail, r.confidence) for r in kg.relations])"
    
    result = evaluate_factscore(kg, text; llm_client=llm_client, confidence_threshold=0.5)
    
    # 5. Assertions
    @test result isa FActScoreResult
    @test result.total_triples == 3
    @test result.supported_triples == 1
    @test result.contradicted_triples == 1
    @test result.not_supported_triples == 1
    
    # Score = supported / total = 1/3
    @test result.factscore ≈ 1/3 atol=0.01
    
    # Verify categories
    @test result.triple_scores[1] == :supported
    @test result.triple_scores[2] == :contradicted
    @test result.triple_scores[3] == :not_supported
    
    @info "FActScore Result: $(result.factscore)"
end
